FROM golang:1.24-alpine AS builder

WORKDIR /app

# 1. Install git to sync all the libraries 
RUN apk add --no-cache git

# 2. Copy all
COPY . .

# Then in the oracle directory
WORKDIR /app
RUN go mod tidy

# 3. Compile everything in the package main (due to .)
RUN go build -ldflags="-w -s" -o /out/oracle .
#RUN go build -tags queue -ldflags="-w -s" -o /out/queue main_queue.go shared_types.go
# AGGIUNTA: Compila anche il tool di verifica!
# Assumendo che il file sia in cmd/check/main.go
RUN go build -ldflags="-w -s" -o /out/checker ./check/status/main.go
RUN go build -ldflags="-w -s" -o /out/manual_checker ./check/manual/main.go

# --- STAGE 2: Runtime ---
FROM alpine:latest

WORKDIR /root/

COPY --from=builder /out/oracle /usr/local/bin/oracle
#COPY --from=builder /out/queue /usr/local/bin/queue
COPY --from=builder /out/checker /usr/local/bin/checker

# Copy the script in the container and make it executable
COPY wait-for-deploy.sh /usr/local/bin/wait-for-deploy.sh
RUN chmod +x /usr/local/bin/wait-for-deploy.sh

# This script is going to be executed every time the container starts
ENTRYPOINT ["/usr/local/bin/wait-for-deploy.sh"]
CMD ["oracle"]